version: '3'

services:
  bot:
    image: ghcr.io/zanotn/events-pi:latest
    restart: unless-stopped
    volumes:
      - db-data:/app/db-data
    environment:
      # Telegram configs:
      # See for more info: https://core.telegram.org/bots#how-do-i-create-a-bot
      # Token of telegram bot
      TELEGRAM_BOT_TOKEN:         
      # Chat id to send reminders
      # Can skip this field at start, go on target chat (with bot) run "/id" and recrate the container with this field
      TELEGRAM_CHAT_ID:

      # Google caledar configs:
      # See for more info: https://support.google.com/a/answer/7378726?hl=en
      GOOGLE_PRIVATE_KEY: # "-----BEGIN PRIVATE KEY-----\n ... \n-----END PRIVATE KEY-----\n"
      GOOGLE_CLIENT_EMAIL:        
      GOOGLE_PROJECT_NUMBER:
      # Calendar id (if is the default put the email of account)      
      GOOGLE_CALENDAR_ID:

      # Bot settings:
      # 1hr: notification 1 hours before
      # 6hr: notification 6 hours before
      # 18: notification at 18:00 of the day before
      # 08-18: notification at 08:00 of the same day if the event start after 18:00 otherwise at 18:00 of the day before
      BOT_REMINDER_TIME: "1hr|6hr|18|08-18"
      # Send an extra message at 14:00 of sunday with all events of the next week (yes|no)
      BOT_WEEKLY_REMINDER: yes
      # Set local time zone, See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ:

volumes:
  db-data: