name: Docker Images for GHCR

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ZanoTN
          password: ${{ secrets.GH_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          provenance: false
          push: true
          tags: ghcr.io/zanotn/events-pi:latest
      - name: Archive Test Results
        run: |
          curl \
            -u ${{ secrets.NTFY_CRED }} \
            -H "EventsPi build" \
            -H "Content-Type: text/plain" \
            -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus build: ${{ job.status}}' \
            ${{ secrets.NTFY_URL }}
